### PR TITLE
Add UseBlankVal property.

### PR DESCRIPTION
**Pull request by yone098**
UseBlankVal is used when you want to output an empty string.
The default value is false, so if it is not set , empty string can not be output .
example

```
writer := NewWriter(&buf)
writer.UseBlankVal = true
```

### CODE REVIEW

**Comment by najeira** [comment]
Thanks!

I think returning error by blank value is a bug.
LTSV should allow blank value.

What do you think about changing this behavior?

**Comment by yone098** [comment]
This library can read blank value.
So, I want to write blank value.

Also I am using this library at business work now, We need to output the blank value.
I would like to change this.

**Comment by najeira** [comment]
Could you send other pull request to accept writing blank value?

**Comment by yone098** [comment]
Yes! Later I'll send other PR.

**Comment by najeira** [comment]
see #3

**Pull request closed without merging**
